export const TIPO_ACTAS: string[] = ['TRANSITO', 'INSPECCION', 'BROMATOLOGIA', 'OBRAS PARTICULARES', 'POLICIA AMBIENTAL']

export const TIPO_ACTUACION: string[] = ['SENTENCIA', 'DECRETO', 'OFICIO', 'NOTIFICACION']

export enum ACTAS {
  TRANSITO = 'TRANSITO',
  INSPECCION = 'INSPECCION',
  BROMATOLOGIA = 'BROMATOLOGIA',
  OBRAS_PARTICULARES = 'OBRAS PARTICULARES',
  POLICIA_AMBIENTAL = 'POLICIA AMBIENTAL'
}

export enum ACTUACION {
  SENTENCIA = 'SENTENCIA',
  DECRETO = 'DECRETO',
  OFICIO = 'OFICIO',
  NOTIFICACION = 'NOTIFICACION'
}

export enum RESPONSABLE {
  SI = 1,
  NO = 0,
}

export const PRIORIDAD_URGENTE = '1'

export const INSPECCION_PREVENTIVAS = [
  { value: 'SECUESTRO', label: 'SECUESTRO' },
  { value: 'CLAUSULA', label: 'CLAUSULA' }
]

export const OBRAS_PREVENTIVAS = [
  { value: 'PARALIZACIÓN DE OBRAS', label: 'PARALIZACIÓN DE OBRAS' }
]

export const DEFAULT_COLOR = '#808080'

export const ART_ALCOHOLEMIA_ID = 214
