export const TIPO_PLANTILLAS: string[] = ['DECRETO', 'SENTENCIA', 'OFICIO', 'NOTIFICACION']

export const TIPO_ACTAS: string[] = ['TRANSITO', 'INSPECCION', 'BROMATOLOGIA', 'OBRAS PARTICULARES']

export enum ACTAS {
    TRANSITO = 'TRANSITO', 
    INSPECCION = 'INSPECCION', 
    BROMATOLOGIA = 'BROMATOLOGIA', 
    OBRAS_PARTICULARES = 'OBRAS PARTICULARES'
}