on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:
jobs:
  run_pull_main:
    name: Deploy Main Branch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands for Main
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 1200s
          script: |
            cd ${{ secrets.WORK_DIR }} 
            git fetch 
            git checkout main
            git pull 
            npm install
            docker stop juzgado-query || true
            docker rm juzgado-query || true
            docker rmi municipalidad/juzgado-query:lastest -f
            docker build --no-cache --build-arg VITE_API_URL='http://137.184.53.136:80/api/v1' --build-arg VITE_TEMPLATE_URL='https://reportes.cc.gob.ar/templateFiles' --build-arg VITE_CARBONE_URL='https://reportes.cc.gob.ar/carbone' --tag municipalidad/juzgado-query:lastest .
            docker run --restart=always --name juzgado-query -d -p 0.0.0.0:5009:80 municipalidad/juzgado-query:lastest
            docker builder prune -f
            docker image prune -a -f
            exit

  run_pull_dev:
    name: Deploy development Branch
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands for development
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_DEV_HOST }}
          username: ${{ secrets.SSH_DEV_USER }}
          password: ${{ secrets.SSH_DEV_PASSWORD }}
          port: ${{ secrets.SSH_DEV_PORT }}
          timeout: 1200s
          script: |
            cd ${{ secrets.DEV_WORK_DIR }} 
            git fetch 
            git checkout development
            git pull 
            npm install
            docker stop juzgado-query-dev
            docker rm juzgado-query-dev
            docker rmi municipalidad/juzgado-query-dev:latest -f
            docker build --no-cache --build-arg VITE_API_URL='https://api-test-juzgado.cc.gob.ar/api/v1' --build-arg VITE_TEMPLATE_URL='https://reportes.cc.gob.ar/templateFiles' --build-arg VITE_CARBONE_URL='https://reportes.cc.gob.ar/carbone' --tag municipalidad/juzgado-query-dev:lastest .
            docker run --restart=always --name juzgado-query-dev -d -p 0.0.0.0:5009:80 municipalidad/juzgado-query-dev:lastest
            docker builder prune -f
            docker image prune -a -f
            exit
