on:
  push:
    branches:
      - main    
  workflow_dispatch:
jobs:
  run_pull_dev:
    name: Deploy main Branch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands for main
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_DEV_HOST }}
          username: ${{ secrets.SSH_DEV_USER }}
          password: ${{ secrets.SSH_DEV_PASSWORD }}
          port: ${{ secrets.SSH_DEV_PORT }}
          timeout: 1200s
          script: |
            cd ${{ secrets.DEV_WORK_DIR }} 
            git fetch 
            git checkout main
            git pull 
            docker stop juzgado-query || true
            docker rm juzgado-query || true
            docker rmi municipalidad/juzgado-query:lastest || true
            docker build --no-cache --build-arg VITE_API_URL='https://api-juzgado.cc.gob.ar/api/v1' --build-arg VITE_TEMPLATE_URL='https://reportes.cc.gob.ar/templateFiles' --build-arg VITE_CARBONE_URL='https://reportes.cc.gob.ar/carbone' --tag  municipalidad/juzgado-query:lastest .
            docker run --restart=always --name juzgado-query -d -p 0.0.0.0:5009:80 municipalidad/juzgado-query:lastest
            docker builder prune || true
            exit
